{
  "comments": [
    {
      "key": {
        "uuid": "90df3ecf_94c4c2df",
        "filename": "front_end/elements/ElementsPanel.js",
        "patchSetId": 4
      },
      "lineNbr": 977,
      "author": {
        "id": 1341669
      },
      "writtenOn": "2020-04-20T22:55:27Z",
      "side": 1,
      "message": "My promise logic is a bit rusty, if the checkRemoteObjectThenReveal rejects, does this revealPromise() function also reject?\n\nI think what I had in mind was a check on the result of pushObjectAsNodeToFrontend(), which would result in the same reject as line 979, but I think this does the same thing, so feel free to leave if so. Just want to make sure the reject msg propagates out of this function.",
      "revId": "fc58d8720a6069b7a4b48603f7de944ee06f8c9e",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "7cfe7f93_f61a0a6c",
        "filename": "front_end/elements/ElementsPanel.js",
        "patchSetId": 4
      },
      "lineNbr": 977,
      "author": {
        "id": 1341633
      },
      "writtenOn": "2020-04-20T23:15:20Z",
      "side": 1,
      "message": "So to my understanding, checkDeferredDOMNodeThenReveal and checkRemoteObjectThenReveal aren\u0027t promises and therefore don\u0027t have their own definitions of resolve/reject.  However, it has access to revealPromise\u0027s resolve/reject which is what it is calling when resolvedNode is null.\n\nI\u0027ll test this and make sure that is the case before checking in.",
      "parentUuid": "90df3ecf_94c4c2df",
      "revId": "fc58d8720a6069b7a4b48603f7de944ee06f8c9e",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}